repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    # trims all whitespace from the end of each line
    -   id: trailing-whitespace
    # ensures that all files end in a newline and only a newline
    -   id: end-of-file-fixer
    # prevents large files from being committed (>100kb)
    -   id: check-added-large-files
        args: [--maxkb=100]
    # enforce the naming conventions of test scripts
    -   id: name-tests-test
        # tests match test_.*\.py
        args: [--pytest-test-first]
        exclude: tests.asserts.*|tests.modules.*|tests/py2puml/parsing/mockedinstance.py

-   repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.21.0
    hooks:
    -   id: commitlint
        stages: [commit-msg]
        additional_dependencies: ['@commitlint/config-angular']

-   repo: https://github.com/PyCQA/isort
    rev: 6.0.0
    hooks:
    -   id: isort
        additional_dependencies: [toml]

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.6
    hooks:
    -   id: ruff
    -   id: ruff-format
